### PR TITLE
Pin Setup View Changes

### PR DESCRIPTION
**Pull request by 0x49b**
I've added some feature to the View 'Pin Setup'. All Microcontrollers are now described in a .json file (src/renderer/src/assets/microcontrollers/microcontrollers.json). When the View gets mounted, this file will be read and the corresponding information will be set. The link between pog.json and this data will be made with the 'controller' field in pog.json and the 'id' field in the microcontrollers.json file. 

I've added 3 fields in the microcontrollers.json to be copyright-law-compliant. These are:

- imageUrl: Here add the original source of the File
- license: The name of the license
- licenseUrl: A Url to the license Text

To add a new microcontroller do the following:

1. Add a new entry in the microcontrollers.json
2. Add the Image of the Microcontroller as a .png file to src/renderer/src/assets/microcontrollers
3. make shure that the id used in the json and the image file name are identical
4. make shure you've set 'image' to true in the .json

If all set correctly, the Pin Setup View should look like this:

image-license-and-origin-source

See the links rendered below the image

### CODE REVIEW

**Comment by JanLunge** [comment]
I like this a lot seems like a good approach, will merge.

**Comment by JanLunge** [comment]
ok might need to check your linter, it removed the imports for the hints, you dont need to commit any fix I will just do that on the main branch

**Comment by 0x49b** [comment]
Ok thx for feedback. Do you use VSCode? So I can import the correct settings

**Comment by JanLunge** [comment]
I am using Jetbrains WebStorm so I don't have a working config for VSCode unfortunately. just the prettier config is setup on this project right now. but you will likely need some vue3 extensions so that it will recognise the variables that are used in the template as well.

**Comment by 0x49b** [comment]
Great, then I will also use Webstorm for further PR's

**Pull request merged**
