### PR TITLE
Feature: Split side configuration

### PR DESCRIPTION
**Pull request by Birkemosen**
Ran into an issue where the split keyboard couldn't reliably use the drivename for detecting the split side.

This adds configuration options under "Matrix" for setting the split configurations.

Add: Keyboard Type selector: Normal | Split (Bluetooth) | Split (Serial) | Split (1 Pin)
Add: Split side detection configuration: Config (left / right) | VBUS (with pin) | Label (drivelabel)

pog.json adds the following fields: keyboardType, splitSide, vbusPin

image

NB: Contains the fixes from the other PR.

### CODE REVIEW

**Comment by JanLunge** [comment]
I added some cleanup for the now not needed split value in the keyboardStore, maybe it is better to put the split config into the pins tab so the pin prefix doesnt get to be too confusing.

**Comment by Birkemosen** [comment]
Makes sense wiht the cleanup and I will try moving the split config to the pins tab.

**Comment by Birkemosen** [comment]
I moved the configuration to pins tab.

image
VBUS not selected:
image
VBUS selected:
image

**Comment by JanLunge** [comment]
Perfect this look really nice, on the initial setup it now feels like its in the right place. I just saw you removed the `use_pio=True` from the split constructor I'm still not sure what would be a good default but on boards not using the standart rx and tx pins this needs to be enabled for it to work on the pi pico rp2040 then there is the `uart_flip` if the pins are just swapped maybe something i should look at in the future to add as additional toggles. just wanted to point it out here. this worked on my normal boards with matrix wiring i will just test it on another split board before merging.

**Comment by JanLunge** [comment]
with the pio true added, my split keyboards works so i will leave that in until i find a need to make it configurable. also i forgot to reset the split pins so that is added now as well.

**Review by JanLunge — APPROVED** [review]

**Comment by Birkemosen** [comment]
I was unsure about the use_pio, so it s perfect that you have added it. Thanks

**Comment by JanLunge** [comment]
its now released with version 1.3.1 https://github.com/JanLunge/pog/releases/tag/v1.3.1 Thanks for your contribution

**Pull request merged**
