### PR TITLE
11 pog on boards without vbus sense

### LINKED ISSUE #11: Pog KMK does not run on boards without VBus sense
When using a controller board that does not define a VBUS_SENSE pin ([many boards lack a built-in VBus detection circuit](https://github.com/bgkendall/keyboard_mcu_list)), Pog’s KMK will fail with the following error:
```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
starting keyboard G33 (01HZ8WB406YBNHA9K16MZK2EK7)
Traceback (most recent call last):
  File "code.py", line 3, in <module>
  File "pog.py", line 112, in <module>
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'VBUS_SENSE'
```
Removing the following line from `pog.json` will fix the issue:
```
    "vbusPin": "VBUS_SENSE",
```
but it is added back whenever the Pog configuration is saved.

### PR DESCRIPTION
**Pull request by parallacks**
Added check for if the vbus pin is even needed and if it's a valid option. Added the pin checker to the `renderPin()` function. 
I've tested this with a rp2040-zero which doesn't have a VBUS_SENSE pin. I haven't tested the 'quickpin' version yet. 

I'm not a huge fan of this implementation overall because it allows incorrect setups to just quietly fail. If a user puts in improper pin numbers their firmware will run but they'll have a hard time figuring out why their keyboard isn't working. I've added a debug message when we find an invalid pin so if they connect to via serial they'll at least see that. It'll be less of an issue when we add the ability to check validity of pins before even creating the pog.json

Marked as draft as I want to test the quickpin before merging.

Fixes #11

### CODE REVIEW

**Comment by JanLunge** [comment]
I like this implementation a lot, I had the idea that error messages could always be send via serial and pog would autoconnect to the serial port of the keyboard (the second serial is also use for the update when the drive is hidden) and then print any errors directly in the gui. Also I already started a serial command to read all the available pins from the board so that the gui could show hints when typing pin names and show an error even before saving. So I would say this PR is a very good step into that direction.

**Comment by parallacks** [comment]
I agree its in the right direction. I should've said I don't like this implementation being the only thing checking. Having the checks that you're working on will greatly reduce the amount of times we'll even need these check. And this PR will catch things if someone tries using a shared pog.json.

**Comment by JanLunge** [comment]
Can i merge this? Seems good enough to me for now

**Comment by JanLunge** [comment]
Yes exactly for quickpin you would need to import your board yourself. Did not find a good way to list compatible quickpin boards yet

**Comment by parallacks** [comment]
Ok sorry for the delay, I've added some extra code to account for quick pin and I've tested it. Should be good to merge now.

**Comment by JanLunge** [comment]
No worries, very nice that you added this for quickpin as well.

**Review by JanLunge — APPROVED** [review]

**Pull request merged**
